language: node_js

branches:
  only:
    - master

install:
  - npm install dockerlint

before_script:
  - bash ./_build_test.sh

script:
  - bash ./_test.sh

notifications:
  email:
    on_success: never

